language: java
matrix:
  include:
    - name: "Linux JDK8"
      os: linux
      dist: xenial
      jdk:
        - openjdk8
      env:
        - TRAVIS_DIST_NAME="trusty"
    - name: "MacOS JDK8"
      os: osx
      osx_image: xcode10.1
#    - name: "Windows" --- Not yet supported
#      os: windows
#      jdk:
#        - openjdk8

install:
  - WD=$PWD
  - cd ..
  - git clone https://github.com/Funz/funz-profile
  - cd $WD

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export HOMEBREW_NO_AUTO_UPDATE=1; rm -f '/usr/local/include/c++'; brew install r libxml2; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null 2> /dev/null ; brew install caskroom/cask/brew-cask 2> /dev/null; brew cask install xquartz; fi
  - if [[ "$TRAVIS_DIST_NAME" == "xenial" ]]; then echo "deb https://cloud.r-project.org/bin/linux/ubuntu xenial-cran35/" | sudo tee -a /etc/apt/sources.list; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install r-recommended r-cran-rgl pandoc --allow-unauthenticated -y; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install pandoc; fi
  - mkdir libR; R -e "install.packages(c('devtools','usethis'),repos = 'http://cran.us.r-project.org',lib='libR')"
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rm -f '/usr/local/include/c++'; brew install ant; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install ant -y; fi
  
script: 
  - ant test

before_deploy:
  - ant clean dist
  - cd dist; zip -r ../algorithm-EGO.zip *; cd ..
  - ant install
  - zip -r FunzR-EGO.zip FunzR-EGO
  
deploy:
  provider: releases
  api_key:
    secure: Q8pCDx6WQVEYdXJSpXI/AHYCdVnLTzLNPGNvXHPAIgxMVmWz8DCRhkFVtQ0VaSDDZq+6f+xcW9L5EE2vDxln+HbZ2Y5If1trxrb489Vamb3bQFCjlKYbwchcqAEgjXWi3Upghq3KHG2GyeySZ+/4LtYRhyy1jPg5nP0YRKznf3DWZfkA6dy+VQIhmxZ7yJ9FCFxCsHiakfl6gm20OLQKEb2YJd0rHxosXEe0olUg5D2iaTmIqX1UiPxacGwd/Yddqk/Aiv8kWlt5/Fyb8/B/eH8kqa/azc8QYt6d+Kpk+KJ3vT7hIW/SaRoup1gGYOEcxPr/fTvNCFtDVTSVJ6H5fL9Mhn/BkJ8Do1vGFMKyGd6kSxk/JtjrrHII64+lPKzBEuTGlnhqGZtJqh1hUyBryvDwX1Lbg9hCAFG3qTOCnZ20qoJU2Kb2iN/9NCwAIOyk+cnMClEfcOzQh4x1NL0loASz9cDcxf/hX4Aj7VqPLn+GeOtEhhT3P1cvThfS3HiHui3W7J8SYI+OVyS3/N0QfLIdRsIxZiDE30D4ssBHuWdZ7bAHQPA0uQDS8g/ceeDX8iVy4WXS5lTynacYJRYDOQm2YRubGHJXeJXl/UzSgGawHepVgUookoiEBpTWOcPwRgUH5jFa2dBmoZiBzwFkfZwhy87WS1lbkjpnT9A1rK0=
  file_glob: true
  file:
    - FunzR-*.zip
    - algorithm-*.zip
  on:
    tags: true
    branch: master
  skip_cleanup: true
  overwrite: true
